version: "3"

services:
  php:
    restart: always
    image:  devilbox/php-fpm:7.4-prod-0.94
    volumes:
      - ${APP_LOCAL_DIR}:${APP_REMOTE_DIR}

  nginx:
    restart: always
    image: nginx:1.17.3
    volumes:
      - ${APP_LOCAL_DIR}:${APP_REMOTE_DIR}:rw
      - ./mount/ssl/:/ssl:ro
      - ./mount/nginx/:/etc/nginx/conf.d/
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    depends_on:
      - database
      - php

  database:
    image: mysql:8
    restart: always
    volumes:
      - ./mount/sql/:/docker-entrypoint-initdb.d/
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  acme:
    image: neilpang/acme.sh
    volumes:
      - ${APP_LOCAL_DIR}:${APP_REMOTE_DIR}:rw
      - ./mount/ssl/:/ssl:rw
    command: acme.sh --issue -d advancedhosting.cloud --force -w ${APP_REMOTE_DIR}/public  --key-file /ssl/private.key --fullchain-file /ssl/certificate.crt --standalone




volumes:
  mysql_volume:


