<?php
/**
 * @package Unlimited Elements
 * @author UniteCMS.net
 * @copyright (C) 2017 Unite CMS, All Rights Reserved. 
 * @license GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 * */
defined('UNLIMITED_ELEMENTS_INC') or die('Restricted access');

GlobalsUC::$arrServerSideText = array(
		"uncategorized"=>esc_html__("Uncategorized", "unlimited_elements"),
		"all_addons"=>esc_html__("All Items", "unlimited_elements"),
		"new_layout"=>esc_html__("New Layout", "unlimited_elements"),
		"import_layout"=>esc_html__("Import Layout", "unlimited_elements"),
		"import_layouts"=>esc_html__("Import Layouts", "unlimited_elements"),
		"layouts_global_settings"=>esc_html__("Layouts Global Settings", "unlimited_elements"),
		"save_layout_settings"=>esc_html__("Save Layout Settings", "unlimited_elements"),
		"no_layouts_found"=>esc_html__("No Layouts Found", "unlimited_elements"),
		"layout_title"=>esc_html__("Layout Title", "unlimited_elements"),
		"edit_layout"=>esc_html__("Edit Layout", "unlimited_elements"),
		"back_to_layouts_list"=>esc_html__("Back to layouts list", "unlimited_elements"),
		"my_layouts"=>esc_html__("My Layouts", "unlimited_elements"),
		"layout_deleted"=>esc_html__("Layout Deleted", "unlimited_elements"),
		"layout_duplicated"=>esc_html__("Layout Duplicated", "unlimited_elements"),
		"all_layouts"=>esc_html__("All Layouts", "unlimited_elements"),
		"layouts_added_successfully"=>esc_html__("Layouts Added Successfully", "unlimited_elements"),
		"uploading_layouts_file"=>esc_html__("Uploading Layouts file...", "unlimited_elements"),
		"layout_created"=>esc_html__("Layout Created", "unlimited_elements"),
		"layout_updated"=>esc_html__("Layout Updated", "unlimited_elements"),
		"layout_imported"=>esc_html__("Layout Imported", "unlimited_elements"),
		"layout_saved"=>esc_html__("Layout Saved", "unlimited_elements"),
		"preview_layout"=>esc_html__("Preview Layout", "unlimited_elements"),
		"manage_layout_categories"=>esc_html__("Manage Layout Categories", "unlimited_elements"),
		"set_category_to_layout"=>esc_html__("Set Category To Layout", "unlimited_elements"),
		"select_layouts_export_file"=>esc_html__("Select layouts export file", "unlimited_elements"),
		"are_you_sure_to_delete_this_layout"=>esc_html__("Are you sure to delete this layout?", "unlimited_elements"),
		"addon_library"=>esc_html__("Addon Library", "unlimited_elements"),
		"search_layout"=>esc_html__("Search Layout", "unlimited_elements"),
);


GlobalsUC::$arrClientSideText = array(
		"empty"=>esc_html__("Empty", "unlimited_elements"),
		"new"=>esc_html__("New", "unlimited_elements"),
		"add_item"=>esc_html__("Add Item","unlimited_elements"),
		"update_item"=>esc_html__("Update Item","unlimited_elements"),
		"edit_item"=>esc_html__("Edit Item","unlimited_elements"),
		"close"=>esc_html__("Close","unlimited_elements"),
		"cancel"=>esc_html__("Cancel","unlimited_elements"),
		"update"=>esc_html__("Update","unlimited_elements"),
		"restore"=>esc_html__("Restore","unlimited_elements"),
		"updating"=>esc_html__("Updating...","unlimited_elements"),
		"restoring"=>esc_html__("Restoring...","unlimited_elements"),
		"import"=>esc_html__("Import","unlimited_elements"),
		"edit"=>esc_html__("Edit","unlimited_elements"),
		"edit_addon"=>esc_html__("Edit Addon","unlimited_elements"),
		"addon_container_settings"=>esc_html__("Addon Container Settings","unlimited_elements"),
		"delete_addon"=>esc_html__("Delete Addon","unlimited_elements"),
		"duplicate_addon"=>esc_html__("Duplicate Addon","unlimited_elements"),
		"updating_categories_order"=>esc_html__("Updating Categories Order...","unlimited_elements"),		
		"set_addon"=>esc_html__("Set Addon","unlimited_elements"),
		"add_addon_to_column"=>esc_html__("Add Addon To Column","unlimited_elements"),
		"removing_addons"=>esc_html__("Removing...","unlimited_elements"),
		"updating_addon_title"=>esc_html__("Updating Title...","unlimited_elements"),
		"duplicating_addons"=>esc_html__("Duplicating...","unlimited_elements"),
		"updating_addons_order"=>esc_html__("Updating Order...","unlimited_elements"),
		"updating_addons"=>esc_html__("Updating...","unlimited_elements"),
		"copying_addons"=>esc_html__("Copying...","unlimited_elements"),
		"moving_addons"=>esc_html__("Moving...","unlimited_elements"),
		"confirm_remove_addons"=>esc_html__("Are you sure you want to delete these addons?","unlimited_elements"),
		"uc_textfield"=>esc_html__("Text Field","unlimited_elements"),
		"uc_textarea"=>esc_html__("Text Area","unlimited_elements"),
		"uc_checkbox"=>esc_html__("Checkbox","unlimited_elements"),
		"uc_dropdown"=>esc_html__("Dropdown","unlimited_elements"),
		"uc_radioboolean"=>esc_html__("Radio Boolean","unlimited_elements"),
		"uc_typography"=>esc_html__("Typography","unlimited_elements"),
		"uc_link"=>esc_html__("Link","unlimited_elements"),
		"uc_number"=>esc_html__("Number","unlimited_elements"),
		"uc_colorpicker"=>esc_html__("Color Picker","unlimited_elements"),
		"uc_editor"=>esc_html__("Editor","unlimited_elements"),
		"uc_icon"=>esc_html__("Icon Picker","unlimited_elements"),
		"uc_icon_library"=>esc_html__("Icon Library","unlimited_elements"),
		"uc_shape"=>esc_html__("Shape Picker","unlimited_elements"),
		"uc_addonpicker"=>esc_html__("Addon Picker","unlimited_elements"),
		"uc_map"=>esc_html__("Google Map Picker","unlimited_elements"),
		"uc_image"=>esc_html__("Image","unlimited_elements"),
		"uc_mp3"=>esc_html__("Audio","unlimited_elements"),
		"uc_post"=>esc_html__("Post","unlimited_elements"),
		"uc_posts_list"=>esc_html__("Posts List","unlimited_elements"),
		"uc_padding"=>esc_html__("Padding","unlimited_elements"),
		"uc_margins"=>esc_html__("Margin","unlimited_elements"),
		"uc_post_terms"=>esc_html__("Post Terms","unlimited_elements"),
		"uc_users"=>esc_html__("Users List","unlimited_elements"),
		"uc_font_override"=>esc_html__("Font Override","unlimited_elements"),
		"uc_imagebase"=>esc_html__("Image Fields","unlimited_elements"),
		"uc_menu"=>esc_html__("Menu","unlimited_elements"),
		
		"uc_slider"=>esc_html__("Slider","unlimited_elements"),
		"uc_background"=>esc_html__("Backgound","unlimited_elements"),
		"uc_border"=>esc_html__("Border","unlimited_elements"),
		"uc_datetime"=>esc_html__("Date Time","unlimited_elements"),
		"uc_textshadow"=>esc_html__("Text Shadow","unlimited_elements"),
		"uc_boxshadow"=>esc_html__("Box Shadow","unlimited_elements"),
		
		"choose_image"=>esc_html__("Choose Image","unlimited_elements"),
		"choose_audio"=>esc_html__("Choose Audio","unlimited_elements"),
		"edit_file"=>esc_html__("Edit File","unlimited_elements"),
		"save"=>esc_html__("Save","unlimited_elements"),
		"delete_op"=>esc_html__("Delete","unlimited_elements"),
		"duplicate_op"=>esc_html__("Duplicate","unlimited_elements"),
		"bulk"=>esc_html__("Bulk","unlimited_elements"),
		"delete_include"=>esc_html__("Delete Include","unlimited_elements"),
		"add_include"=>esc_html__("Add Include","unlimited_elements"),
		"include_settings"=>esc_html__("Include Settings","unlimited_elements"),
		"always"=>esc_html__("Always","unlimited_elements"),
		"never_include"=>esc_html__("Never Include","unlimited_elements"),
		"not_selected"=>esc_html__("Not Selected","unlimited_elements"),
		"choose_addon"=>esc_html__("Choose Addon","unlimited_elements"),
		
		"delete_row"=>esc_html__("Delete Row","unlimited_elements"),
		"duplicate_row"=>esc_html__("Duplicate Row","unlimited_elements"),
		"copy_row"=>esc_html__("Copy Row","unlimited_elements"),
		"delete_section"=>esc_html__("Delete Section","unlimited_elements"),
		"duplicate_section"=>esc_html__("Duplicate Section","unlimited_elements"),
		"copy_section"=>esc_html__("Copy Section","unlimited_elements"),
		"paste_section"=>esc_html__("Paste Section","unlimited_elements"),
		"save_to_library"=>esc_html__("Save To Library","unlimited_elements"),
		"in_buffer"=>esc_html__("In Buffer","unlimited_elements"),
		"delete_column"=>esc_html__("Delete Column","unlimited_elements"),
		"duplicate_column"=>esc_html__("Duplicate Column","unlimited_elements"),
		"column_settings"=>esc_html__("Column Settings","unlimited_elements"),
		"add_column"=>esc_html__("Add Column","unlimited_elements"),
		"move_row"=>esc_html__("Move Row","unlimited_elements"),
		"move_section"=>esc_html__("Move Section","unlimited_elements"),
		"move_column"=>esc_html__("Move Column","unlimited_elements"),
		"move_addon"=>esc_html__("Move Addon","unlimited_elements"),
		"settings"=>esc_html__("Settings","unlimited_elements"),
		"row"=>esc_html__("Row","unlimited_elements"),
		"section"=>esc_html__("Section","unlimited_elements"),
		"row_layout"=>esc_html__("Row Layout", "unlimited_elements"),
		"more_actions"=>esc_html__("More Actions", "unlimited_elements"),
		"less_actions"=>esc_html__("Less Actions", "unlimited_elements"),
		"hidden_row"=>esc_html__("Hidden Row", "unlimited_elements"),
		"hidden_column"=>esc_html__("Hidden Column", "unlimited_elements"),
		"hidden_addon"=>esc_html__("Hidden Addon", "unlimited_elements"),
		"section_anchor"=>esc_html__("Section Anchor", "unlimited_elements"),
);

$filepathProviderClientText = GlobalsUC::$pathProvider."provider_client_text.php";

if(file_exists($filepathProviderClientText))
	require $filepathProviderClientText;
